### ISSUE TITLE
CoffeeScript 2 support

### ISSUE THREAD

**Issue by michaelforrest** [webpack-contrib/coffee-loader#39] opened 2017-05-26 10:53 UTC
I'd like to try [CoffeeScript 2](http://coffeescript.org/v2)  in my project but I get `coffee-loader@0.7.3 requires a peer of coffee-script@1.x but none was installed`.

I'll see what happens if I change this and submit a PR if it seems to work okay?

**Comment by michaelforrest** [comment] 2017-05-26 10:54
Or I could try this for now https://github.com/iHaiduk/coffee-loader/commit/9e759db1e79fd83eff145604422561f3437fbe19

**Comment by evilebottnawi** [comment] 2017-05-26 11:49
@michaelforrest seems CoffeeScripts v2 in beta, i think it is breaking changes. Let's wait stable release and upgrade loader deps

**Comment by buhrmi** [comment] 2017-06-28 09:54
So it looks like the peerDependencies in `package.json` have been updated to work with coffeescript 2, but the the package version was kept at `0.7.3`. Could you update the version (probably 0.8.0) and publish it on npm?

**Comment by beeplin** [comment] 2017-06-30 04:09
agree. The previous commit (https://github.com/webpack-contrib/coffee-loader/commit/5c5e35a3e584b8cdb690c1a059e03bc16a56957b) has done the coffeescript2 support, but not published to npm yet.

**Comment by molszanski** [comment] 2017-07-27 16:59
Npm publish pls? :) Even with a beta tag

**Comment by buhrmi** [comment] 2017-07-27 18:05
what's the holdup? we're all waiting :o

**Comment by objectkit** [comment] 2017-08-01 22:54
finger drumming

**Comment by molszanski** [comment] 2017-08-02 11:27
Or add this to package.json
`"coffee-loader": "github:webpack-contrib/coffee-loader#0ea4d6a7cc9ffc7c8f7a0c6eb3fd3fedea9943b8",`

**Comment by iixixv** [comment] 2017-08-03 08:29
By requiring coffeescript instead of coffee-script in line 5 in 'node_modules/coffee-loader/index.js' did work for me and i was able to use jsx as v2 supports.
i don't know if an 'or' could do for both coffee-script, coffeescript

**Comment by edmiester777** [comment] 2017-08-23 01:59
The workaround that I use is to define a module alias. The package module-alias helps you do this.
`npm i --save module-alias`

Then I have my package.json like this:

```json
    "_moduleAliases": {
        "coffee-script": "node_modules/coffeescript/lib/coffeescript"
    }
```

And I just call `require('module-alias/register')` at the beginning of my application and it reroutes the "coffee-script" require to the new "coffeescript" require for CS2.

**Comment by evilebottnawi** [comment] 2017-08-23 09:22
If someone is interested in helping with `coffee-loader` PR welcome.

**Comment by renchap** [comment] 2017-08-23 09:27
@evilebottnawi https://github.com/webpack-contrib/coffee-loader/commit/5c5e35a3e584b8cdb690c1a059e03bc16a56957b switched from `coffee-script` to `coffeescript` (the new package name). This allows using `coffee-loader` with CoffeeScript 1 and CoffeeScript 2 (with `coffeescript@beta`).

The problem is that `coffee-loader` has not been released on NPM, so people need to rely on the git version or some hacks. If you can get a new `coffee-loader` released on NPM, this would solve the issue :)

**Comment by evilebottnawi** [comment] 2017-08-23 09:29
@renchap Send request on release in `slack`, thanks!

**Comment by beeplin** [comment] 2017-08-23 16:05
thanks @evilebottnawi . That would be a life saver! 👍

**Comment by d3viant0ne** [comment] 2017-08-23 18:56
@renchap - Latest master has been released as `0.8.0`. Changelog with the permanent information for this release can be found [here](https://github.com/webpack-contrib/coffee-loader/blob/master/CHANGELOG.md#080-2017-08-23)

**Comment by renchap** [comment] 2017-08-23 19:14
@d3viant0ne Thanks a lot!
I can confirm CoffeeScript 2 integration works with Webpack (2.6). My package.json contains:

```json
{
  "dependencies": {
    "coffeescript": "next",
    "coffee-loader": "^0.8.0"
  }
}
```

This issue should be closed.

**Closed** 2017-08-23 22:30 UTC
Labels: priority: 5 (nice to have), semver: Major, type: Feature

**Comment by chabib** [comment] 2017-09-29 06:09
Does anybody use coffescript 2 in vue component? I am trying to get it works, but still failing.

Here's the code:

component.vue
```
...

<script lang="coffee">
import Logo from '~/components/Logo.vue'

export default
  components:
    {
      Logo
    }

  data: ->
    id: 1
</script>

...
```

package.json

```
...

  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "coffee-loader": "^0.8.0",
    "coffeescript": "^2.0.1",
    "eslint": "^4.3.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-html": "^3.1.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.1.1",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-standard": "^3.0.1",
    "pug": "^2.0.0-rc.4",
    "pug-loader": "^2.3.0",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.1"
  }

...
```

**Comment by chabib** [comment] 2017-09-29 06:29
Welp, looks like when using coffescript I have to disable eslint

**Comment by garviand** [comment] 2018-01-15 22:13
Still get the same error 

in package.json
```
"coffee-loader": "0.9.x",
"coffeescript": "2.1.x",
```

error:
```
Error: ./views/js/main.coffee
Module parse failed: Unexpected token (17:11)
You may need an appropriate loader to handle this file type.
```

**Comment by molszanski** [comment] 2018-01-16 07:12
@garviand, what do you mean by "the same"?

Just to be sure, have you tried completely removing node_modules and reinstalling it again? Just to make sure you are really using the latest versions?

**Comment by garviand** [comment] 2018-01-16 22:44
An error on my end. I was compiling coffeescript before calling webpack functions... Sorry!
