### ISSUE TITLE
Produces duplicate code

### ISSUE THREAD

**Issue by binarykitchen** [webpack-contrib/coffee-loader#60] opened 2018-03-14 20:57 UTC
```
eval("var portal;\n\nportal = __webpack_require____webpack_require__(/*! portal */ \"./src/modules/portal.es\"/*! portal */ \"./src/modules/portal.es\");\n\nportal.init();\n\n\n//# sourceURL=webpack:///./src/modules/portal-abc.coffee?");
```

with Webpack v4.1.1 any coffeescript code is duplicated. Known issue?

**Comment by michael-ciniawsky** [comment] 2018-03-15 07:44
Could you provide a minimal reproduction repo ? t

There are similar claims/issues popping up

- https://github.com/webpack/webpack/issues/6748
- https://github.com/jantimon/html-webpack-plugin/issues/898#issuecomment-373059636

 but the root cause isn't tracked down yet as it seems

**Comment by sokra** [comment] 2018-03-15 08:43
Closing as duplicate

**Closed by sokra** 2018-03-15 08:43 UTC
Labels: priority: 4 (important), severity: 2 (regression), status: Needs repro, type: Bug
